### ISSUE TITLE
joining forces?

### ISSUE THREAD

**Issue by DiTo97** [prakashngit/Python-Sandbox-for-Langchain-Agents#1]
hey @prakashngit,

I had a look at your sandbox package, and I like the idea of exposing the service both as an API (but leaning towards FAPI) as well as a LangChain tool available to a standard agent, while having limited IO capabilities handling a workspace.

some time ago, I [forked ai-code-sandbox](https://github.com/DiTo97/ai-code-sandbox/tree/patch-1) and have been working on improving the code generation sandbox ever since. I have taken a slightly different approach to IO capabilities, added requirements handling, declarative sandbox config definitions, and support to Node.js other than Python.

I was about to wrap it all up in an API and expose a few LangChain-compliant agentic tools — requirements handling, IO and code execution — when I found your repository and thought we might join forces and make the sandbox tool even better.

thoughts on that? happy to talk about it whenever

**Comment by prakashngit** [comment]
@DiTo97 Thank you for the interest and the comments. Yes, it would be good to understand more about your sandbox requirements. Though the current tool that I built is a python-shell that a react-like agent can use as a tool, the framework can in principle be extended to other scenarios as well. I will connect with you via linkedin, and we can chat more. thanks!

**Comment by DiTo97** [comment]
closing, will text on LI!
